### ISSUE TITLE
Dingo\Api\Dispatcher not respecting route

### ISSUE THREAD

**Issue by arthurkirkosa** [dingo/api#808] opened 2016-01-11 20:43 UTC
The App Controller
```php
<?php

namespace App\Http\Controllers;

class CustomersController extends Controller
{
    /**
     * @var Dingo\Api\Dispatcher
     */
    protected $dispatcher;

    /**
     * Initialize
     *
     * @param Dingo\Api\Dispatcher $dispatcher
     */
    public function __construct(Dispatcher $dispatcher)
    {
        $this->middleware('auth');

        $this->dispatcher = $dispatcher;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = $this->dispatcher->version('v0')->get('customers');
        // $customers = Customer::all();

        return view('customers.index', compact('customers'));
    }
...
}
```

The API Controller
```php
<?php

namespace App\Http\Controllers\Api\V0;

class CustomersController extends Controller
{
    /**
     * Initialize
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Customer::all();
    }
...
}
```

The Test
```php
...
    /** @test */
    public function it_creates_a_new_customer()
    {
        $store = factory(Store::class)->create();

        $dummy = factory(Customer::class)->make([
            'store_id' => $store->id,
        ]);

        $this->visit(route('customers.create'))
             ->see('Adauga un client nou.')
             ->select($store->id, 'store_id')
             ->type($dummy->first_name, 'first_name')
             ->type($dummy->last_name, 'last_name')
             ->type($dummy->email, 'email')
             ->type($dummy->phone, 'phone')
             ->press('Add')
             ->seePageIs(route('customers.index')) // **This is not working anymore**
             ->see($dummy->name);

        $data = array_only($dummy->toArray(), [
            'first_name', 'last_name',
            'phone', 'email',
        ]);

        $this->seeInDatabase('customers', $data);

        $customer = Customer::first();

        $this->assertEquals("{$dummy->first_name} {$dummy->last_name}", $customer->name);
        $this->assertNotNull($customer->token);
    }
...
```

The ```$this->seePageIs(route('customers.index'))``` is not working anymore; it records as being still on the create page.
```
1) CustomerTest::it_creates_a_new_customer
Did not land on expected page [http://localhost/customers].

Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://localhost/customers'
+'http://localhost/customers/create'
```

This all works well if I comment out this code ```$customers = $this->dispatcher->version('v0')->get('customers');``` from the Controller and leave the Eloquent object in.

It works well if I view the ```customers.index``` route in the browser. Even adding a new customer works well in the browser.

**Comment by jasonlewis** [comment] 2016-01-26 06:30
Might be an issue with the resetting of the request/route object. I'll check it out when I can.

**Comment by kerbylav** [comment] 2016-02-16 06:59
I think it is the same issue with routing when making internal requests:

```php
$dispatcher = app('Dingo\Api\Dispatcher');
$dispatcher->get('/api/users/100000');
dd(Route::current());
```

```
Route {#555 ▼
  #adapter: Laravel {#223 ▶}
  #container: Application {#2 ▶}
  #request: null
  #uri: "/api/users/{id}"
  #methods: array:2 [▶]
  #action: array:9 [▶]
  #versions: array:1 [▶]
  #scopes: null
  #authProviders: null
  #rateLimit: null
  #rateExpiration: null
  #throttle: null
  #controller: null
  #method: null
  #conditionalRequest: true
  #middleware: null
}
```

Current route is API route instead of real route

**Comment by assembledadam** [comment] 2016-03-08 17:03
I'm thinking this might be related to something that's broken for me since I upgraded from the Laravel 4.2 version (and installation) to Laravel 5 and v1.0.0 Beta 2.

When an internal route is not found, subsequent request seem to fail. E.g. 
````
try {
    $row = \API::header('Content-Type', 'application/json')->get('blahblah');
} catch (\Symfony\Component\HttpKernel\Exception\NotFoundHttpException $e) {

}

````

**Comment by assembledadam** [comment] 2016-03-08 20:28
I've been trying to debug this, it is a strange one. @jasonlewis maybe you can shed some light on this behaviour. For my case above, here's what I can see happening:

 - At the moment of dispatch, the requestStack has two requests - the original 'parent' request and the request currently being made to the API.
 - In my case, running in CLI, the original 'parent' request has no route (route() on the request returns null).
 - When successful, refreshRequestStack() pops the internal one off the end, leaving us with the original 'parent' request again.  But the original request has been altered, and now has a route...! The route matches the internal request that was popped off the end of the request stack.
- When there's a http exception, refreshRequestStack() pops the internal request off the end, the same behavour.  But the original 'parent' request has NOT been altered in this instance, and so the route is still null.

This is the source of my error when dispatch() attempts to get the current route ($this-router->getCurrentRoute()), giving me that null error message above.

In my case (above), dispatch() determines the response is a http 404, enters the catch block for HttpExceptionInterface errors, runs refreshRequestStack() and then throws the exception.

It seems like the fix is to assign a route of some kind to the parent on failure, as it does when successful.

Any ideas?

**Comment by jasonlewis** [comment] 2016-03-09 03:03
So I managed to solve the initial issue described. It was simply a matter of ensuring that any subsequent requests made prior to an internal request is added to the request stack. Basically, the parent request in the dispatcher was incorrect because the crawler had made another request (which differed from the initial one).

As for what you're seeing @assembledadam, I'm not able to reproduce this. I copied your code exactly and I get the 404 error, not a `FatalErrorException`.

Can you provide any more information here? Perhaps upgrade Dingo to `1.0.*@dev` to get the latest `dev-master` changes as they're pushed up.

**Comment by assembledadam** [comment] 2016-03-09 16:34
Hi @jasonlewis, thanks for the reply, but I'm using the latest version.

I have created a clean test case for you to review: https://github.com/assembledadam/laravel/commit/621954b87ab0fa61967578bebd0dc3cbe073e5fd

If you checkout that repo and run `php artisan testcase` in the app root, you'll get the error. File to tinker is app/Console/Commands/Test.php.

The issue can be fixed in src/Routing/Router.php on line 676:

Replace
```
return $this->currentRoute = $this->createRoute($request->route());
```
With
````
if ($route = $request->route()) {
    return $this->currentRoute = $this->createRoute($route);
}

return $this->currentRoute = null;
````

And the output represents the expected behaviour.

**Comment by jasonlewis** [comment] 2016-03-10 07:22
I see now, this will only occur when you don't fire off an external request to begin with. In your case you're using a test. Let me mess around a bit, see what we can do.

**Comment by assembledadam** [comment] 2016-03-10 09:43
Well there is no external request because it's via the CLI - this is the case with my intended usage too (a migration/ETL script which gathers and inserts data into API).

**Comment by jasonlewis** [comment] 2016-03-10 11:59
Yeah it's all cool. Still tinkering and what not. Trying to set it all straight.

**Comment by jasonlewis** [comment] 2016-03-10 13:31
Things should be working as intended now. Still trying to sort some Lumen stuff out though.

**Comment by arthurkirkosa** [comment] 2016-03-10 13:44
Now the validation from the request object is not coming back correctly.

All old values are empty.

**Comment by jasonlewis** [comment] 2016-03-10 13:45
Lovely.

Laravel or Lumen @arthurkirkosa?

**Comment by arthurkirkosa** [comment] 2016-03-10 13:45
Laravel 5.2.22

**Comment by jasonlewis** [comment] 2016-03-10 13:47
I probably won't get a chance to investigate much more tonight, so you'll have to hang tight.

**Comment by arthurkirkosa** [comment] 2016-03-10 13:47
It's ok...

**Comment by jasonlewis** [comment] 2016-03-10 13:48
Oh, @arthurkirkosa, is this during a regular request to the API or through the CLI (testing)?

**Comment by arthurkirkosa** [comment] 2016-03-10 13:50
Both.

I've also booted a server and tried to create an entity through the form.

The thing is, I'm not doing anything through dingo. I'll investigate more myself and post here what I find.

I'll try using older versions of dingo and see if it has to do anything with the issues I'm seeing.

**Comment by jasonlewis** [comment] 2016-03-10 13:53
Yeah, try checking out the last few commits and testing it. It's been a fiddly mess that's for sure. I want to talk to Taylor about a few things as well.

Keep me posted on how you go.

**Comment by arthurkirkosa** [comment] 2016-03-10 13:56
https://github.com/dingo/api/commit/05cbc2918e118ad71a0f44dfd754552c7388c27e

This build broke it.

**Comment by arthurkirkosa** [comment] 2016-03-10 14:00
Gave you access to the bitbucket repo if you wanna play around with the code.

CustomerTest is one of the tests that has failing tests (last one)

**Comment by jasonlewis** [comment] 2016-03-10 14:04
When you say old values you mean flash data? Related to #874 perhaps?

**Comment by arthurkirkosa** [comment] 2016-03-10 14:06
Yes, flashed data.

And it seams that the middleware are not loaded correctly?

**Comment by jasonlewis** [comment] 2016-03-10 14:10
Okay, I'm aware of the sessions being closed twice issue.

Is the not loading correctly related to the commit above? Going to need more details so I'm able to reproduce.

**Comment by arthurkirkosa** [comment] 2016-03-10 14:14
After updating to 05cbc2918e118ad71a0f44dfd754552c7388c27e the issue appears. 

The composer.lock on bitbucket has the last good commit and it give you green tests. (8ac53fb18e845f5a9b8a9cc52ab52b3aea8f08bb this one)

The issue is not related to the original issue from this ticket.

**Comment by assembledadam** [comment] 2016-03-10 14:15
Looks good from the code for the issue I was reporting, thanks mate (a cleaner version of what I wrote!).

**Comment by jasonlewis** [comment] 2016-03-10 14:18
@arthurkirkosa, let's move the session discussion to #874.

@assembledadam, awesome, thanks for the report. Yeah, pretty much was just what you posted. Had to tweak a few other things as well (mainly Lumen stuff).

**Comment by arthurkirkosa** [comment] 2016-03-10 14:19
Sure

**Closed by jasonlewis** 2016-03-10 14:18 UTC
Labels: bug
