### ISSUE TITLE
Router set fluent name issue

### ISSUE THREAD

**Issue by antonkomarev** [dingo/api#1185] opened 2016-09-04 20:42 UTC
Hello guys, I found an issue, here is a test for it.

``` php
public function testGroupAsPrefixesRouteAsFluentNameAs()
{
    $this->router->version('v1', ['as' => 'api'], function ($api) {
        $api->get('users', function () {
            return 'foo';
        })->name('users');
    });

    $routes = $this->router->getRoutes('v1');

    $this->assertInstanceOf('Dingo\Api\Routing\Route', $routes->getByName('api.users'));
}
```

The problem with fluent name setter `name()`.

Generated name will be `apiusers` but not the `api.users`.

Even if you write first as like this `['as' => 'api.']` it will generate same _wrong_ result.

**Comment by hengsoheak** [comment] 2016-11-07 13:51
There are no any respond sosssssssssss

**Comment by catalinux** [comment] 2016-11-08 13:14
What framework? What version? Lumen/Laraverl, 5.X?

**Comment by a-komarev** [comment] 2016-11-08 13:24
I've tested on clean Laravel 5.3.6 install.

**Comment by chuoke** [comment] 2019-05-17 05:17
This problem still here, It seems to be caused by dingo in ` dingo/api/src/Routing/Router.php `

```php

    /**
     * Merge the given group attributes.
     *
     * @param array $new
     * @param array $old
     *
     * @return array
     */
    protected function mergeGroup(array $new, array $old)
    {
        $new['namespace'] = $this->formatNamespace($new, $old);

        $new['prefix'] = $this->formatPrefix($new, $old);

        foreach (['middleware', 'providers', 'scopes', 'before', 'after'] as $option) {
            $new[$option] = $this->formatArrayBasedOption($option, $new);
        }

        if (isset($new['domain'])) {
            unset($old['domain']);
        }

        if (isset($new['conditionalRequest'])) {
            unset($old['conditionalRequest']);
        }

        if (isset($new['uses'])) {
            $new['uses'] = $this->formatUses($new, $old);
        }

        $new['where'] = array_merge(Arr::get($old, 'where', []), Arr::get($new, 'where', []));

        if (isset($old['as'])) {
            $new['as'] = trim($old['as'].'.'.Arr::get($new, 'as', ''), '.');
        }

        return array_merge_recursive(array_except($old, ['namespace', 'prefix', 'where', 'as']), $new);
    }

```

 The most key part:

```php
if (isset($old['as'])) {
    $new['as'] = trim($old['as'].'.'.Arr::get($new, 'as', ''), '.');
}
```

**Comment by chuoke** [comment] 2019-05-21 10:20
finally，I find the right way , the '.' should be `name('.users')`, that will be show `api.users`.
maybe should close this

**Closed** 2019-07-22 08:02 UTC
