### ISSUE TITLE
Disable logging of exceptions in production environment

### ISSUE THREAD

**Issue by fabianlaule** [dingo/api#699] opened 2015-10-23 20:52 UTC
Currently, every exception will be logged in the logfile which is unnecessary. Unfortunately, there is no possibility to disable it. 
[This method](https://github.com/dingo/api/blob/51901c3dda0ccf099a8a2515141e5a0fdbd402bf/src/Exception/Handler.php#L123) should not be called on HttpKernel or Dingo specific exceptions to prevent a fast growing log file with unnecessary entries.

An example of a thrown and logged exception:
```
production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException' with message ...
Stack trace: 
....
```

**Comment by jasonlewis** [comment] 2015-11-03 03:12
No I think it's more than that. The default kernel has the ability to not report certain exceptions, which I think `HttpException` is a part of. So, by default, none of those exceptions are being reported. I'll need to mimic this functionality as best I can, as errors still need to be reported, just not all of them.

**Comment by alextyrey** [comment] 2015-12-31 03:46
Was going to submit a PR that addresses this but..

@jasonlewis is there a reason Dingo's exception handler can't just copy the functionality of Laravel's $dontReport?

I feel like your above comment implies that the issue is more complex than I think it is.

**Comment by lvandyk** [comment] 2016-01-19 13:46
Any update on this? Also needed to disable logging entirely on production for now.

**Comment by jasonlewis** [comment] 2016-02-26 11:02
A fix for this will be pushed in the next update.

**Closed by jasonlewis** 2016-02-26 11:02 UTC
Labels: bug

**Comment by lvandyk** [comment] 2016-02-26 11:03
Awesome thanks Jason!

**Comment by fabianlaule** [comment] 2016-02-26 11:45
Perfect, thanks Jason :+1:
