### ISSUE TITLE
Lumen 5.2 incomplete docs generated

### ISSUE THREAD

**Issue by sefsinalas** [dingo/api#921] opened 2016-03-21 18:49 UTC
Hello. I have 2 project with Lumen + Dingo.
The first with lumen 5.1 and it generates the docs correctly.
But in the second, with lumen 5.2, when I run php artisan api:docs to generate they are generated incompletly. Its apears to be a random 'thing' depending on the position of the route in routes.php

Sometimes the docs for a controller is generated correctly, but when I change the position of the route, then, sometimes, the docs for that controller are not generated.

Can you help me?

**Comment by Bantes** [comment] 2016-03-22 13:42
The package don't support of Lumen 5.2 now

**Comment by jasonlewis** [comment] 2016-03-23 03:54
I'll take a look, thanks. Shouldn't be much difference between 5.1 and 5.2. Both are supported.

**Comment by crynobone** [comment] 2016-03-23 04:17
Would confirm having similar problem with Lumen 5.2

**Comment by jasonlewis** [comment] 2016-03-31 11:29
Has anyone been able to determine what exactly causes the mysterious disappearing? Are you placing it after or before a normal route that does it? Another controller without docs? What's different about the placement that would cause this to happen?

Ping @crynobone @sefsinalas

**Comment by sefsinalas** [comment] 2016-03-31 13:04
I dont really understand what's happening. These are some examples of routes. In bold the routes that does generate the docs.

```
<?php

$api = app('Dingo\Api\Routing\Router');

$api->version('v1', ['prefix' => 'api'], function ($api) {

	/*========================================
    =            Listados simples            =
    ========================================*/
**    $api->get('group', 'App\Http\Controllers\GroupController@index');**
**    $api->get('cuisine_type', 'App\Http\Controllers\CuisineTypeController@index');**
    $api->get('commerce_type', 'App\Http\Controllers\CommerceTypeController@index');

	/*=================================
    =            Mailchimp            =
    =================================*/
    $api->post('mailchimp', 'App\Http\Controllers\MailchimpController@store');

	/*================================
    =            Comercio            =
    ================================*/
**    $api->get('commerce', 'App\Http\Controllers\CommerceController@index');**
   ** $api->get('commerce/{id}', 'App\Http\Controllers\CommerceController@show');**

    /*===============================
    =            Pedidos            =
    ===============================*/
    $api->post('order', 'App\Http\Controllers\OrderController@store');

	/*===================================
	=            Ubicaciones            =
	===================================*/
**    $api->get('location/countries', 'App\Http\Controllers\LocationController@countries');**
   ** $api->get('location/{id}/provinces', 'App\Http\Controllers\LocationController@provinces');**
**    $api->get('location/{id}/locations', 'App\Http\Controllers\LocationController@locations');**
   ** $api->get('location/{id}/zones', 'App\Http\Controllers\LocationController@zones');**
**    $api->get('location', 'App\Http\Controllers\LocationController@show');**

    /*================================
    =            Reservas            =
    ================================*/
    $api->post('reservation', 'App\Http\Controllers\ReservationController@store');

    /*================================
    =            Contacto            =
    ================================*/
    $api->post('contact/send', 'App\Http\Controllers\ContactController@send');


});
```

And now the changing a little the position of some routes:

```
<?php

$api = app('Dingo\Api\Routing\Router');

$api->version('v1', ['prefix' => 'api'], function ($api) {

	/*========================================
    =            Listados simples            =
    ========================================*/
**    $api->get('group', 'App\Http\Controllers\GroupController@index');**
   ** $api->get('cuisine_type', 'App\Http\Controllers\CuisineTypeController@index');**
**    $api->get('commerce_type', 'App\Http\Controllers\CommerceTypeController@index');**


	/*================================
    =            Comercio            =
    ================================*/
   ** $api->get('commerce', 'App\Http\Controllers\CommerceController@index');**
    **$api->get('commerce/{id}', 'App\Http\Controllers\CommerceController@show');**

    /*===============================
    =            Pedidos            =
    ===============================*/
**    $api->post('order', 'App\Http\Controllers\OrderController@store');**

	/*===================================
	=            Ubicaciones            =
	===================================*/
**    $api->get('location/countries', 'App\Http\Controllers\LocationController@countries');**
   ** $api->get('location/{id}/provinces', 'App\Http\Controllers\LocationController@provinces');**
**    $api->get('location/{id}/locations', 'App\Http\Controllers\LocationController@locations');**
   ** $api->get('location/{id}/zones', 'App\Http\Controllers\LocationController@zones');**
**    $api->get('location', 'App\Http\Controllers\LocationController@show');**

    /*================================
    =            Contacto            =
    ================================*/
    $api->post('contact/send', 'App\Http\Controllers\ContactController@send');

    /*=================================
    =            Mailchimp            =
    =================================*/
    $api->post('mailchimp', 'App\Http\Controllers\MailchimpController@store');

    /*================================
    =            Reservas            =
    ================================*/
    $api->post('reservation', 'App\Http\Controllers\ReservationController@store');

});
```


And one more time

```
<?php

$api = app('Dingo\Api\Routing\Router');

$api->version('v1', ['prefix' => 'api'], function ($api) {


	/*================================
    =            Comercio            =
    ================================*/
**    $api->get('commerce', 'App\Http\Controllers\CommerceController@index');**
  ** $api->get('commerce/{id}', 'App\Http\Controllers\CommerceController@show');**

    /*===============================
    =            Pedidos            =
    ===============================*/
    **$api->post('order', 'App\Http\Controllers\OrderController@store');**

    /*================================
    =            Contacto            =
    ================================*/
    $api->post('contact/send', 'App\Http\Controllers\ContactController@send');

    /*=================================
    =            Mailchimp            =
    =================================*/
    $api->post('mailchimp', 'App\Http\Controllers\MailchimpController@store');

    /*================================
    =            Reservas            =
    ================================*/
    $api->post('reservation', 'App\Http\Controllers\ReservationController@store');

    /*===================================
	=            Ubicaciones            =
	===================================*/
**    $api->get('location/countries', 'App\Http\Controllers\LocationController@countries');**
   ** $api->get('location/{id}/provinces', 'App\Http\Controllers\LocationController@provinces');**
    **$api->get('location/{id}/locations', 'App\Http\Controllers\LocationController@locations');**
**    $api->get('location/{id}/zones', 'App\Http\Controllers\LocationController@zones');**
   ** $api->get('location', 'App\Http\Controllers\LocationController@show');**

    /*========================================
    =            Listados simples            =
    ========================================*/
    $api->get('group', 'App\Http\Controllers\GroupController@index');
    $api->get('cuisine_type', 'App\Http\Controllers\CuisineTypeController@index');
    $api->get('commerce_type', 'App\Http\Controllers\CommerceTypeController@index');

});
```

**Comment by sefsinalas** [comment] 2016-03-31 13:05
I cant figure out a pattern.

**Comment by jasonlewis** [comment] 2016-04-01 01:47
Any chance you can get this on GitHub, including your controllers?

Just remove any fluff from the controllers, like actual method logic, I just need the docs so I can try and generate it and see what's going on. I tried to recreate all your controllers with basic docs and it worked fine. So going to need to see all relevant docs/controllers/routes.

**Comment by crynobone** [comment] 2016-04-01 02:06
@jasonlewis 

It would generate the missing api documentation (for that single controller) if I comment all other routes.  Otherwise blueprint seem to ignore the controller.

**Comment by jasonlewis** [comment] 2016-04-01 02:11
What's different about the controller though?

I really have no idea how to replicate this still...

**Comment by crynobone** [comment] 2016-04-01 02:12
```php
<?php

namespace App\Lumen\Http\Controllers;

use Dingo\Api\Http\Response;
use Illuminate\Contracts\Auth\Authenticatable;

/**
 * User Profile.
 *
 * @Resource("User Profile", uri="/profile")
 */
class ProfileController extends Controller
{
    /**
     * Current User Profile.
     *
     * @Get(uri="/")
     * @Request(headers={"Authorization": "Bearer xxx"})
     * @Transaction({
     *     @Response(200, body={"id": 1, "email": "xxx", "address": "", "phone_number": "0123456789", "phone_mobile": "0123456789", "identification": "", "fullname": "xxx", "status": 1, "meta": {}, "created_at": "2015-09-06 11:06:45", "updated_at": "2015-09-06 11:06:45"}),
     *     @Response(401, body={"message": "Token has expired", "status_code": 401})
     * })
     */
    public function show(Authenticatable $user)
    {
        return new Response($user->toArray(), 200);
    }
}
```

```php
<?php

$api = app(Dingo\Api\Routing\Router::class);

/*
|--------------------------------------------------------------------------
| Application API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the API routes for an application.
| It is a breeze. Simply tell Lumen the URIs it should respond to
| and give it the Closure to call when that URI is requested.
|
*/

$api->version(['v1'], ['namespace' => 'App\Lumen\Http\Controllers'], function ($api) {
    $api->get('/', 'WelcomeController@hello');

    $api->post('auth', 'AuthController@authenticate');
    $api->get('auth/refresh', ['middleware' => 'api.auth', 'uses' => 'AuthController@refresh']);

    $api->group(['middleware' => ['api.auth', 'api.throttle']], function ($api) {
        $api->delete('auth', 'AuthController@deauthenticate');

        $api->get('profile', 'ProfileController@show');
    });
});
```

**Comment by jasonlewis** [comment] 2016-04-01 02:19
So you've only got docs for that one method?

**Comment by sefsinalas** [comment] 2016-04-01 18:48
I will upload the project to github tomorrow. Thanks for your help

**Comment by sefsinalas** [comment] 2016-04-04 18:25
https://github.com/sefsinalas/testdocs

**Comment by jasonlewis** [comment] 2016-04-05 02:32
@sefsinalas You just need to update Dingo. You're on an older commit. This issue stems from some differences between FastRoute versions which was fixed in 9ada1d349e4794bdf587c85bc2702e401f0e87ae. Static routes are now normalized correctly so they're added.

I ran a `composer update` and all docs were generated successfully.

@crynobone possibly the same issue? Are you up to date?

**Comment by sefsinalas** [comment] 2016-04-05 19:10
That fixed the docs for me :smile: 

Thanks a lot

**Comment by sefsinalas** [comment] 2016-08-10 20:35
I'm facing the same issue again. And this time I already ran composer update.

Can anybody help me?

**Comment by hskrasek** [comment] 2016-08-16 02:18
@sefsinalas Is it possible you reverted back to an older commit somehow? Would have to see if Lumen changed versions of FastRoute, or if FastRoute had a regression that broke the fix.

**Comment by specialtactics** [comment] 2019-06-21 00:25
Closing because old and no response

**Closed by specialtactics** 2019-06-21 00:25 UTC
Labels: bug
