### ISSUE TITLE
php artisan api:routes error on laravel 8

### ISSUE THREAD

**Issue by cacing69** [dingo/api#1770] opened 2021-03-01 14:54 UTC
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.12
| Package version   | 3.0.5
| PHP version       | 7.4.15

#### Actual Behaviour

i got error when use command **php artisan api:route**

#### Expected Behaviour

it must show route api list
![image](https://user-images.githubusercontent.com/36250619/109514522-b4379c00-7ad8-11eb-8dc9-04fb930ed330.png)

**Comment by xuechu** [comment] 2021-03-02 20:10
me too.
Framework version 8.28.0

**Comment by xuechu** [comment] 2021-03-02 20:11
v8.28.0
Fixed
Fix undefined property with sole query (#36216)
Resolving non-instantiables corrupts Container::$with (#36212)
Fix attribute nesting on anonymous components (#36240)
Ensure $prefix is a string (#36254)
Add missing import (#34569)
Align PHP 8.1 behavior of e() (#36262)
Ensure null values won't break on PHP 8.1 (#36264)
Handle directive $value as a string (#36260)
Use explicit flag as default sorting (#36261)
### Fix middleware group display (d9e28dc)

**Comment by cherrynechou** [comment] 2021-03-04 04:04
me too.

**Comment by hamza-younas94** [comment] 2021-03-05 11:50
getting same error

**Comment by mrodriguezt** [comment] 2021-03-05 17:35
me too

**Comment by xbrunosousa** [comment] 2021-03-07 04:39
same here

**Comment by cacing69** [comment] 2021-03-09 04:31
but php artisan route:list, work for me,

**Comment by gonpre** [comment] 2021-03-09 06:30
The problem is a change done in this commit on https://github.com/laravel/framework

https://github.com/laravel/framework/commit/d9e28dcb1f4a5638b33829d919bd7417321ab39e

**Comment by kfoon** [comment] 2021-03-18 13:44
> The issue is caused by the change done in this commit [laravel/framework@d9e28dc](https://github.com/laravel/framework/commit/d9e28dcb1f4a5638b33829d919bd7417321ab39e)

so how do we resolve this?

**Comment by gonpre** [comment] 2021-03-18 19:14
> > The issue is caused by the change done in this commit [laravel/framework@d9e28dc](https://github.com/laravel/framework/commit/d9e28dcb1f4a5638b33829d919bd7417321ab39e)
> 
> so how do we resolve this?

What I did was to add this code:

```
    /**
     * Flush the router's middleware groups.
     *
     * @return $this
     */
    public function flushMiddlewareGroups()
    {
        return $this;
    }
```

on the file `vendor/dingo/api/src/Routing/Router.php` to be able to run the `api:routes` command.

**Comment by bastienu** [comment] 2021-03-18 19:31
Thanks a lot, it fixed everything. Are you going to make a PR @gonpre?

**Comment by gonpre** [comment] 2021-03-18 20:44
> Thanks a lot, it fixed everything. Are you going to make a PR @gonpre?

yes, I already did, hope this could be merged soon

**Comment by cacing69** [comment] 2021-03-19 14:30
> > Thanks a lot, it fixed everything. Are you going to make a PR @gonpre?
> 
> yes, I already did, hope this could be merged soon

i will close this issue when yout PR has been merged

**Comment by MrEldin** [comment] 2021-04-02 22:14
Will this ever be merged?

**Comment by gonpre** [comment] 2021-04-02 22:46
> Will this ever be merged?

no idea, meanwhile I changed my composer file to use my repo with the fix instead, maybe this will help you too

```
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/gonpre/api"
        }
    ],
    "require": {
        "dingo/api": "dev-bugfix/1770_api_routes_error_laravel_8",
```

**Comment by cacing69** [comment] 2021-04-03 01:17
> Will this ever be merged?

https://github.com/dingo/api/pull/1771#issuecomment-811459676 refer to this, maybe no

**Comment by vytsci** [comment] 2021-04-06 10:04
Same issue here. Its stupid that such errors might occur, why Laravel does not provide any interface for router?

**Comment by specialtactics** [comment] 2021-04-30 11:05
Hey guys, this fix is merged and tagged, thanks for your patience.

https://github.com/dingo/api/releases/tag/v3.0.6

**Closed by specialtactics** 2021-04-30 11:05 UTC
