### ISSUE TITLE
api endpoints break after dingo/api update from 1.0.0-beta8 to 2.0.0-alpha1

### ISSUE THREAD

**Issue by hermannatz** [dingo/api#1600] opened 2018-10-08 10:56 UTC
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel|
| Framework version | 5.6.*
| Package version   | 2.0.0-alpha1
| PHP version       | 7.1.3

#### Actual Behaviour

All api call are not working anymore, I get a 500 status_code error

#### Expected Behaviour

After update, I expected my api endpoints to work as usual

#### Possible Solutions

no ideas yet

**Comment by specialtactics** [comment] 2018-10-16 09:40
Given you are updating from version 1.x.x to 2.x.x of something, I think it is wrong to expect everything to "work as usual". '

I am not sure what the general upgrade guide is, but I would recommend you don't do this update unless you are willing to change your code to fit the new version, but anyhow this is not a bug.

**Comment by unlockr** [comment] 2018-12-07 16:34
We have the same problem, I think is due to depreciation of PHP artisan. 
After the update, we get the api routes not working. It can be fixed by running `php artisan api:cache` but it's really annoying... Hope this can be fixed soon

**Closed** 2019-01-25 01:56 UTC
