### ISSUE TITLE
laravel5.5 local.ERROR: get_class() expects parameter 1 to be object, null given

### ISSUE THREAD

**Issue by lambq** [dingo/api#1572] opened 2018-07-10 17:40 UTC
## error message

local.ERROR: get_class() expects parameter 1 to be object, null given {"exception":"[object] (ErrorException(code: 0): get_class() expects parameter 1 to be object, null given at /www/wwwroot/api.rsyun.net/you/vendor/dingo/api/src/Http/Response/Factory.php:126

**Comment by specialtactics** [comment] 2019-02-05 13:16
Closing this - please use the new issue format, as it's not clear at all what the problem is or what is happening to cause it.

**Closed by specialtactics** 2019-02-05 13:16 UTC

**Comment by stevenmyhre** [comment] 2019-12-13 23:12
I am having this same issue, if I call 
```$this->reponse()->item(null, new DefaultTransformer())```

@specialtactics The Response/Factory `item` method should check for null item before calling get_class() due to php 7.2 decision to throw if given a null argument:

[https://www.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.no-null-to-get_class](https://www.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.no-null-to-get_class)

**Comment by specialtactics** [comment] 2020-03-12 04:52
Thanks @stevenmyhre , fixed that issue just now:
https://github.com/dingo/api/pull/1718
