### ISSUE TITLE
[L5] Redirect issue when Dingo API installed

### ISSUE THREAD

**Issue by joselfonseca** [dingo/api#463] opened 2015-06-11 21:57 UTC
Hey there!, i am adding dingo to an existing Laravel 5 app and i've been able to manage pretty much everything well, but, if i have a redirect response in the app i get this error:

```
ErrorException in Router.php line 554:
Argument 1 passed to Dingo\Api\Routing\Router::prepareResponse() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\RedirectResponse given, called in /home/forge/alamesa.dev/vendor/dingo/api/src/Routing/Router.php on line 541 and defined
```
Thanks!

**Comment by jasonlewis** [comment] 2015-06-13 03:46
You're redirecting in an API endpoint? You shouldn't be.

**Comment by joselfonseca** [comment] 2015-06-13 03:57
Not an API endpoint, And i know an API should not have any views, the thing is that i have to add some API endpoints to an existing admin panel for an iPhone APP, this is a requirement for the project i am working on for a client. I was looking at the Router and i could not figure out a way to work around it, first thing that came to my mind was to create a class that extends dingo Router and override the method, however i did not try it. I understand if this is not an actual issue if the API is a separate from the admin panel, but in my case it is not. I wanted to know if there was any way around this. Thanks Again!

**Comment by jasonlewis** [comment] 2015-06-18 03:07
The API endpoints should *never* return views. Ever. It should return data. That's it.

I feel like I'm missing something though. Please show some code or something so I can get a better idea of what it is you're trying to achieve.

**Comment by joselfonseca** [comment] 2015-06-18 04:13
Thanks for Reply, I don't think is necessary since i was able to manage the fact that an API should not have views and the Admin Panel should be a separate app, I turned my use case in favor of the api.

However, if you do `return redirect()->to('/home')` in a laravel APP that has Dingo installed, it brakes since the response being returned from the controller is not an instance of `Illuminate\Http\Response`, it is an instance of `Illuminate\Http\RedirectResponse` in `Dingo\Api\Routing\Router::prepareResponse()`. But like i said, i turn my use case in favor to not use an admin panel in the same API project. I will close this as is not really a package issue when the use case is in the package context and purpose.

**Comment by jasonlewis** [comment] 2015-06-18 04:36
Returning a redirect response from a route that has nothing to do with the
API shouldn't break, even with Dingo installed. If that's the case then
it's a bug. I'll test this when I can, but I just don't see how it would
break as the Dingo router will never touch routes outside of its scope.

**Comment by vugtis** [comment] 2015-06-18 05:16
Hello. I encountered the same issue. After digging a little bit, I found out that what I want is 'Making an Internal Request' as instructed on https://github.com/dingo/api/wiki/Internal-Requests.
I think @joselfonseca  maybe want the same thing.

I think here is the case :
- There is an App with Admin Panel
- He create API with Dingo package
- When he send request using Form in his App (Admin Panel), he ends up calling API endpoint within Dingo, and by the logic of his App (Admin Panel), i.e. wrong password, he redirects it to somewhere i.e. Login Page, which shouldn't be done. His solution was to separate Admin Panel and his API app, which is why he close this issue.

What I think is separating Admin Panel App and the API is too much work, instead consuming API endpoint in Admin Panel App in same project via internal request should do the trick.

However, I find out that explanation on Wiki is obsolete and I have trouble calling an internal request.
@jasonlewis Can you point me in the right direction to do internal request in Laravel 5.1 with current Dingo package? Or should I open new issue?
@joselfonseca I am sorry if I misinterpret your case.

**Comment by lightvision** [comment] 2015-06-18 05:19
Internal request works as expected but I susspect that I will have some troubles with data validations through Form Request as well. I have not time to digg today because I'm working on the frontend of may app, but I will provide feedback very soon.

**Comment by vugtis** [comment] 2015-06-18 05:37
Can you hint me how to do it so I can do some trial and error on my own?
I have this on my routes.php :
```sh 
$api->version('v1',['prefix' => 'api','protected' => false], function ($api) {
    $api->get('check',function() {
        return "ok";
    });
});
```
Normally, I reach this code via :
```sh
localhost/MyApp/public/api/check
```
And now I want to do internal request from another Controller I have.
Can you give me a little snippet how to do it? Since the one on wiki can't be used. Or maybe I am missing something. I can't use API facade and can't find ControllerTrait.

**Comment by lightvision** [comment] 2015-06-18 05:48
Get an instance of api.dispatcher from the IoC (in the controller where you want to make an internal request):
```
$api_dispatcher = app()['api.dispatcher'];
```
then call the dispatcher, for example:
```
$user = $api_dispatcher->version('v1')->get('users');
dd($user);
```
The paramenter of the ``get`` is an api route. I've specified the ``version('v1)`` because I want to be clear to what api version is called internally, but is not required. If not provided it will fall back to last version.

Off topic: It should be nice to call a route by its name :)

**Comment by vugtis** [comment] 2015-06-18 06:10
@lightvision Thank you  . It works beautifully.

**Comment by JoeDawson** [comment] 2015-06-22 10:31
Hey!

I'm receiving a similar thing I believe, I got the same error at least...

```
Argument 1 passed to Dingo\Api\Routing\Router::prepareResponse() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\RedirectResponse given, called in /projectname/vendor/dingo/api/src/Routing/Router.php on line 541 and defined
```

This is actually something I'm getting when accessing routes on my existing project, that worked prior to installing.

For example, in my existing L5.1 app - when access the `/login` route - which by the way is nothing in relation to my API routes and attempt to log in (has always worked) - it throws the above error.

Does it have anything to do with the redirect happening in that route? Again, none of this is tied directly to my API what so ever.

Any help here would be **greatly** appreciated!

**Comment by joselfonseca** [comment] 2015-06-22 20:17
@JoeDawson That is the same issue i have. Installing dingo in a working laravel APP Brakes the laravel responses.

Say you want to have an API, if you only issue JSON responses across the entire project, no issues are found and that is great, an API should be it's own project anyways. But if you have an existing APP and you want to add some API endpoints to that project, install Dingo and then the APP routes that return a redirect response brake. 

The thing now is that it seems to be braking any other route. Check this out:

This is my route

```
Route::group(['prefix' => 'backend'], function () {
	Route::get('/login', [
		'as' => 'LaravelAdminLogin',
		'uses' => 'Joselfonseca\LaravelAdmin\Http\Controllers\LoginController@getLogin'
	]);
});
```
I haven't add the Laravel provider `Dingo\Api\Provider\LaravelServiceProvider`

I get this

![screen shot 2015-06-22 at 3 05 19 pm](https://cloud.githubusercontent.com/assets/2046653/8291595/25a2fafc-18f0-11e5-8927-415fbb69a682.png)

Once I add the provider i get this

![screen shot 2015-06-22 at 3 06 55 pm](https://cloud.githubusercontent.com/assets/2046653/8291631/5c4aa870-18f0-11e5-9809-d379bf85f9a7.png)

Now, it use to just mess with the redirect responses, now it seems to get in the way for every route in the app. 

Weird thing is that i look at the provider and i don't see where the original Laravel router is being replace by dingo's, if it is not being replace then i should not touch the routes outside it's scope at all, but it is somehow. 

This is an issue that comes when dingo API is added to an existing project or a project that is not meant to only deliver API endpoints. 

@jasonlewis I hope this information helps somehow. If you need any more info i will be more that happy to help. Thanks for this awesome project.

**Comment by jasonlewis** [comment] 2015-07-09 00:40
There was an issue with how routes were being detected as API routes. Can you all update Dingo and let me know if these problems are persisting.

**Comment by joselfonseca** [comment] 2015-07-15 02:59
Hey @jasonlewis i just installed in a fresh laravel installation along with other packages that has views. Everything seems to be ok.

- Redirect responses from the original app works
- Api Endpoints work as expected.

My issue is solved, Thanks!

**Comment by joselfonseca** [comment] 2015-07-15 03:00
@jasonlewis Not sure if we should wait for others to reply or if this can be close. I will leave it up to you. Thanks again!

**Comment by jasonlewis** [comment] 2015-07-17 11:38
I'm going to close for now as all my tests have executed successfully. If anything resurfaces feel free to ping here or simply open another issue. Cheers. :smile:

**Closed by jasonlewis** 2015-07-17 11:38 UTC

**Comment by kylestev** [comment] 2015-07-18 22:42
@jasonlewis Hi I'm encountering the same exact issue/error as Jose and Joe have described above. Fresh install of Laravel (`5.1.7 (LTS)`) and Dingo ([`dev-master dbb4d82`](https://github.com/dingo/api/commit/dbb4d820eb6b5bd2a4f6668ce0593f5f67c23121) aka the latest commit).

I have 3 non-dingo routes where one is a homepage, one is a login page, and the last is a `POST` route to handle the credentials for logging in. If the user is not logged in and tries to visit the homepage, they are redirected to the login route. This causes the same issue to arise as others have detailed above:

```
Argument 1 passed to Dingo\Api\Routing\Router::prepareResponse() must be an instance of Illuminate\Http\Response, Illuminate\Http\RedirectResponse given
```

Since the `redirect()` helper function that Laravel provides returns an instance of `Illuminate\Http\RedirectResponse` whose base class is: `Symfony\Component\HttpFoundation\RedirectResponse` which is not an instance of `Illuminate\Http\Response`, I believe this is what is causing my issue.

Shouldn't Dingo be ignoring non-API route responses?

Let me know if there is any additional information I can supply to help you debug/reproduce this issue.

**Comment by jasonlewis** [comment] 2015-07-18 22:45
It should yes, make sure you've configured a domain or prefix for the API
to operate on so it doesn't interfere with regular routes.

**Comment by kylestev** [comment] 2015-07-18 22:45
I do have an `API_PREFIX` defined that does not conflict with the other routes.

**Comment by kylestev** [comment] 2015-07-18 22:48
Ahhh @jasonlewis I figured out my issue... I had defined both an `API_DOMAIN` and `API_PREFIX`. My apologies! Removing the `API_DOMAIN` has fixed everything.

I totally missed this line in the Wiki:

> A prefix or subdomain is required, but only one.

Have a nice day!

**Comment by jasonlewis** [comment] 2015-07-18 22:49
Awesome, that was going to be my next question. Only one is required. :smile:

**Comment by ww285276792** [comment] 2017-09-19 03:36
@joselfonseca how do you solve the problem，can you give some code please！
