### ISSUE TITLE
dingo installation problem

### ISSUE THREAD

**Issue by ethirion** [dingo/api#1626] opened 2019-02-28 18:34 UTC
hi, I get this error when I try to install dingo on fresh laravel 5.8 
![untitled](https://user-images.githubusercontent.com/33138958/53589337-5ea41e00-3ba4-11e9-848d-e8497383efc9.png)

**Comment by mallardduck** [comment] 2019-02-28 20:21
Duplicate of #1624.

**Closed** 2019-03-02 10:53 UTC
