### ISSUE TITLE
Internal Request Not Found 404

### ISSUE THREAD

**Issue by allocenx** [dingo/api#809] opened 2016-01-12 11:50 UTC
So i have this annoying problem. Whatever i make or do i always get a not found exception when trying to make an internal requests.

Routes.php

```php
$api = app('Dingo\Api\Routing\Router');
$api->version('v1', function ($api) {

    $api->get('accounts', [
        'as' => 'accounts.all',
        'uses' => 'Hekate\Api\v1\Controllers\AccountsController@getAll'
    ]);

    $api->get('account/{id}', [
        'as' => 'account.one',
        'uses' => 'Hekate\Api\v1\Controllers\AccountsController@getOne'
    ])->where('id', '[a-zA-Z0-9]+');

    $api->get('account/{id}/characters', [
        'as' => 'account.characters',
        'uses' => 'Hekate\Api\v1\Controllers\AccountsController@getCharacters'
    ])->where('id', '[a-zA-Z0-9]+');

    $api->post('login', [
        'as' => 'account.login',
        'uses' => 'Hekate\Api\v1\Controllers\AccountsController@doLogin'
    ]);
});
```

AccountsController.php

```php
    public function getOne($id)
    {
        $data = Account::where(ctype_digit($id) ? 'UserNum' : 'ID', '=', $id)->first();

        if (empty($data)) $this->response->errorNotFound("Account {$id} could not be found.");

        return $data;
    }

    public function getCharacters($id)
    {
        return $this->api->version('v1')->get('accounts');

        //return Server::where(DB::raw('CharacterIdx/8'), '=', ctype_digit($id) ? $id : $this->getOne($id)->UserNum)->get();
    }
```

I am trying to make an internal requests in getCharacters, but i always get not found exception, please help someone.

**Comment by allocenx** [comment] 2016-01-15 13:21
For fucking god sake, anyone knows something?

**Comment by catalinux** [comment] 2016-01-15 13:30
Could you change a little bit the formatting. Also, please detail. What do you mean by "make an internal requests"

**Comment by allocenx** [comment] 2016-01-15 13:42
https://github.com/dingo/api/wiki/Internal-Requests,

See? 
For example a make a route like /test and in this route i use the dispatcher to make an internal api request call but it always gives me 404 not found.

For ex. this code from wiki:
Route::get('/', function () use ($dispatcher) {
    $users = $dispatcher->get('api/users');

    return View::make('index')->with('users', $users);
});

I make exactly how the docs says and still i get 404.

**Comment by jbardnz** [comment] 2016-01-18 05:10
I think this line:
    return $this->api->version('v1')->get('accounts');

needs to include the api prefix, so:
    return $this->api->version('v1')->get('api/accounts');

**Comment by allocenx** [comment] 2016-01-18 07:19
Nop, i tried that too, in a matter a fact,i've tried everything, nothing seems to be working.

**Comment by allocenx** [comment] 2016-01-18 08:52
Anyone?

**Comment by savah** [comment] 2016-01-21 08:12
same problem here. It was working though at some point in the past so I guess an update broke things.

**Comment by allocenx** [comment] 2016-01-21 08:19
And what the hell, does anybody know a fix at least?

**Comment by savah** [comment] 2016-01-21 08:22
Obviously not... Back into trying to trace the error into Dingo and Laravel maze.

**Comment by allocenx** [comment] 2016-01-21 08:34
I see, if you find anything, could you let me know?

**Comment by savah** [comment] 2016-01-21 13:28
I found what was causing the problem. The problem lies in this commit https://github.com/dingo/api/commit/e43f0679ec37c1c0a58c08480e64787afa3377f0 .

This change in dispatcher produces a full url and this doesnt produce a match when the router of laravel searches for the route.

My routes are declarer like `$api->get( 'users/fetchAll', [
		'as'   => 'users.fetchall',
		'uses' => 'App\Api\Controllers\UserController@fetchAll'
	] );` so laravel (class UriValidator implements ValidatorInterface on Illuminate/Routing/Matching/UriValidator.php line 21) `return preg_match($route->getCompiled()->getRegex(), rawurldecode($path));` was searching for a match on '/api/users/fetchAll' whereas the path was /project_name/public/api/users/fetchAll and this never matched therefore the 404.

**Comment by jasonlewis** [comment] 2016-01-26 06:58
> For fucking god sake, anyone knows something?

Chill, mate.

> And what the hell, does anybody know a fix at least?

Can I ask if you're doing this on Laravel/Lumen and what version? 5.1 is preferable at this point in time. I just tested out the code you pasted and internal requests are working fine.

As for @savah, that commit should not cause any issues what so ever. If you've got your projects being served from `/project_name/public` then you've incorrectly set Laravel up, as the `public` directory SHOULD be the root of your project. It should not appear in the URL.

**Comment by allocenx** [comment] 2016-01-26 08:14
I'm using the latest version of laravel 5.2, i guess i did not make the public the root directory, as i am accesing.../public/api/account

**Comment by jasonlewis** [comment] 2016-01-26 08:23
Laravel 5.2 still hasn't been officially merged in.

Your `public` directory should not be in the URL.

**Comment by allocenx** [comment] 2016-01-26 08:31
I see thank you. I'm gonna test this later after i go home from work. I'll let you know if it worked.

**Comment by jasonlewis** [comment] 2016-01-26 08:33
Cheers mate, keep me posted.

**Comment by savah** [comment] 2016-01-26 08:42
I am using 5.1 and whereas internal requests *were* working at some point during November and December when i was last working in this project, they have stopped working without any reason whatsoever. The only thing that has changed in the project was the updated versions of laravel and dingo using composer.

I tried going through the sources with xdebug and just commenting out this fixed my problem and the internal requests are working fine once again. I believe that my laravel is set up correctly since I dont have any other problems with I/O and routing.

**Comment by savah** [comment] 2016-02-05 08:35
@jasonlewis what you say is true and this might be the cause of the problems with dingo. public appears in my urls. What error have i done in the configuration?

**Comment by jasonlewis** [comment] 2016-02-08 01:20
There's a few ways to go about it @savah. Normally, in your Nginx or Apache configuration you'd set the root for the project to point at the `public` directory itself. That way you don't need to add `public` in your URLs.

You can also use `.htaccess` if you're using Apache to get around it. But it's better to simply update your virtual hosts.

**Closed by jasonlewis** 2016-02-08 01:20 UTC
