### ISSUE TITLE
Laravel's response objects.

### ISSUE THREAD

**Issue by bweston92** [dingo/api#474] opened 2015-06-19 14:48 UTC
Using Laravel's Requests for validation ect throws an exception. Somewhere this is being created into a json response but Dingo doesn't like it.

```
Argument 1 passed to Dingo\Api\Routing\Router::prepareResponse() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\JsonResponse given, called in /var/www/fundbay.co.uk/packages/application/vendor/dingo/api/src/Routing/Router.php on line 541
```

**Comment by ghprod** [comment] 2015-06-19 18:11
Yes, its because `$this->validate` automatically return instance of `Illuminate\Http\JsonResponse` if request was AJAX .. workaround for right now maybe we should using manual validator

```php
$validator = Validator::make($payload, $rules);

        if ($validator->fails()) {
            throw new Dingo\Api\Exception\StoreResourceFailedException('Could not create new user.', $validator->errors());
        }
```

waiting for other for better idea :)

**Comment by bweston92** [comment] 2015-06-19 18:13
Actually, I like the fact I'm not having to put it in my controller, one of the main reasons I've upgraded. I'd prefer if this sort of stuff works or has a very similar method.

**Comment by ghprod** [comment] 2015-06-19 18:16
Yes, i'd like to write code like this too :+1: 

![image](https://cloud.githubusercontent.com/assets/1922652/8259862/03d438f8-16ea-11e5-96e9-0b411a416520.png)

**Comment by vugtis** [comment] 2015-06-19 20:28
Yeah, same problem I had today. I fix it this way.
```sh
try {
	$this->validate($request, [
        'id' => 'required', 'password' => 'required',
    ]);
}
catch(IlluminateException\HttpResponseException $e) {
    return $this->response->array(['message'=>$e->getResponse()->getContent(),'status_code'=>$e->getResponse()->getStatusCode()]);

}
```
And don't forget this :

```sh
use Symfony\Component\HttpKernel\Exception;
use Illuminate\Http\Exception as IlluminateException;
```

Some note aside : If you use code above as internal request, it will throw an error. Some modification are still needed.

**Comment by ghprod** [comment] 2015-06-19 22:26
@vugtis wow, nice, at least we can use `$this->request` .. hehhee ..

Thanks

**Comment by jasonlewis** [comment] 2015-06-20 02:38
Duplicate of #462. I'll take a look at this today folks, see what I can come up with.

**Closed by jasonlewis** 2015-06-20 02:38 UTC
