### ISSUE TITLE
Trnasformer is not including 'include' with collection

### ISSUE THREAD

**Issue by iamrutvik** [dingo/api#1141] opened 2016-08-03 11:18 UTC
Hi,

**Here is my transformer :** 

`
<?php
namespace  App\Transformers;
use App\Ride as Ride;
use App\User;
use App\Place;
use App\RideMeta;
use ArrayObject;
class RideTransformer extends \League\Fractal\TransformerAbstract
{
    protected $defaultIncludes = [
        'posted_by', 'from', 'to', 'meta', 'rideusers'
    ];

    public function transform(Ride $ride)
    {

        $ride = [
            'id' => (int)$ride->id,
            'ride_time' => $ride->ride_time,
            'max_rider' => $ride->max_rider,
            'is_started_on_time' => $ride->is_started_on_time,
            'is_ended_on_time' => $ride->is_ended_on_time,
            'ride_started_at' => $ride->ride_started_at,
            'ride_ended_at' => $ride->ride_ended_at,
            'is_active' => $ride->is_active,
        ];

        return $ride;
    }

    /**
     * Include User
     *
     * @param Ride $ride
     * @return \League\Fractal\Resource\Item
     */
    public function includePostedBy(Ride $ride)
    {
        $user = User::find($ride->user_id);
        return $this->item($user, new UserTransformer);
    }
    /**
     * Include from place
     *
     * @param Ride $ride
     * @return \League\Fractal\Resource\Item
     */
    public function includeFrom(Ride $ride)
    {
        $from = Place::find($ride->from_place_id);
        return $this->item($from, new PlaceTransformer);
    }

    /**
     * Include to place
     *
     * @param Ride $ride
     * @return \League\Fractal\Resource\Item
     */
    public function includeTo(Ride $ride)
    {
        $to = Place::find($ride->to_place_id);
        return $this->item($to, new PlaceTransformer);
    }

    /**
     * Include to ride meta
     *
     * @param Ride $ride
     * @return \League\Fractal\Resource\Item
     */
    public function includeMeta(Ride $ride)
    {
        $meta = $ride->meta;
        return $this->collection($meta, new RideMetaTransformer);
    }

    /**
     * Include to ride users
     *
     * @param Ride $ride
     * @return \League\Fractal\Resource\Item
     */
    public function includeRideusers(Ride $ride)
    {
        $rideusers = $ride->rideUsers;
        return $this->collection($rideusers, new RideUserTransformer);
    }
}
?>
'

**My Controller  :**

When I called by index method, it returned error : 

`Call to undefined method Illuminate\\Database\\Query\\Builder::posted_by()`

What is the problem? Where am I doing wrong?

**Comment by tr33m4n** [comment] 2016-08-03 15:58
Hi there,

Have you included the "posted_by" method in your model?

Cheers,

**Comment by georaldc** [comment] 2016-08-03 17:53
As mentioned by @tr33m4n, your model needs to have the includes you are calling as relationship methods. Basically, all your includes need to exist as relationships due to eager loading when they are needed.

https://github.com/dingo/api/wiki/Transformers#automatic-relationship-eager-loading

Also, because of eager loading, you probably might be better off relying on your relationships instead of explicitly making find() calls in your transformer.

**Comment by iamrutvik** [comment] 2016-08-03 19:04
Hi,

Why would it be needed to add it in model? As you can see it in My transformer, I am fetching its details from User model. The ride model has user_id as a field and I am just fetching it using : 

`$user = User::find($ride->user_id);`

All I would be need a includePostedBy  Method in transformer which will automatically called if I have added `posted_by` in `$defaultIncludes` array.
Let me know, If you have any solution in mind? I would try to implement it.

@georaldc : Yeah I agree, I am just not able to figure out Many to many relationship in Laravel, Once I do, will change the code.

**Comment by georaldc** [comment] 2016-08-03 19:24
@iamrutvik Dingo (not fractal) implicitly tries to pre-load what you are trying to "include" by using what each include is named as basis to call the right relationship methods in your model. That's why you get errors like ```Call to undefined method Illuminate\\Database\\Query\\Builder::posted_by()```

https://github.com/dingo/api/blob/master/src/Transformer/Adapter/Fractal.php#L89

**Comment by iamrutvik** [comment] 2016-08-04 05:04
Okay I got it. But that triggered a new Question in mind : 

I did same while fetching a single ride:

`$response = $ride->find($id);
return $this->response->item($response, new RideTransformer())->setMeta($meta);`

This code returns expected result using transformers. Why is it so?

**Comment by georaldc** [comment] 2016-08-04 05:29
Dingo only eager loads automatically when working with a collection. Your code with a single object will work, even if you add some includes because you'll be lazy loading in your model's related resources.

**Comment by hskrasek** [comment] 2016-08-18 03:18
@iamrutvik Looks like the issue you were running into was resolved, I'm gonna close this out. Feel free to re-open if the issue isn't resolved.

**Closed by hskrasek** 2016-08-18 03:18 UTC
Labels: discussion
